### ISSUE TITLE
Segmentation fault for 4 samples / 32 samples tested at run_trycycler_cluster.nf step

### ISSUE THREAD

**Issue by nandan75** [Sydney-Informatics-Hub/ONT-bacpac-nf#21]
**Describe the bug**

An error similar (same) as the one we are experiencing - unresolved in Trycycler github issue - https://github.com/rrwick/Trycycler/issues/48
``` 
**script :** modules/run_trycycler_cluster.nf



*** caught segfault ***
  address 0x38, cause 'memory not mapped'
  
  Traceback:
   1: fastme.bal(distances)
  An irrecoverable exception occurred. R is aborting now ...
  Traceback (most recent call last):
    File "/usr/local/bin/trycycler", line 10, in <module>
      sys.exit(main())
    File "/usr/local/lib/python3.10/site-packages/trycycler/__main__.py", line 41, in main
      cluster(args)
    File "/usr/local/lib/python3.10/site-packages/trycycler/cluster.py", line 43, in cluster
      build_tree(seq_names, seqs, depths, matrix, args.out_dir, cluster_numbers)
    File "/usr/local/lib/python3.10/site-packages/trycycler/cluster.py", line 264, in build_tree
      subprocess.check_output(['Rscript', tree_script])
    File "/usr/local/lib/python3.10/subprocess.py", line 421, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/usr/local/lib/python3.10/subprocess.py", line 526, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['Rscript', '/jobfs/121429820.gadi-pbs/tmphjxv6bbz/tree.R']' died with <Signals.SIGSEGV: 11>.
```
 - The error (segmentation fault) was specifically observed for **4 samples in the _Vibrio-Tenacci_ dataset** (16 samples) and None of the barcodes in the staph experiment (16 samples) 
    - Samples affected: barcode12, barcode13, barcode14,  barcode15  
 - The bash pipeline and its results were checked
    - It was confirmed that this error was actually present in the output for these samples (so not a new bug due to nextflow)
    - Increasing memory was not useful ; the actual memory used was much less than what was allocated. The reason for such error is defined as `accessing memory that “does not belong to you.”`
    - Why was it not caught before 
        -  Improper handling of the next step in the bash-pipeline (only finishing of this step was checked to run the next step)
        - **More ever**: For each of the 4 affected samples the required output "cluster_*/1_contigs" for this step was properly created.
        - **In addition**, the final assemblies and consensus assemblies followed by bakta annotations and busco QC etc were consistent with expected numbers.
        - This suggests that the `segmentation fault` is associated with an end step "AFTER" the required output is generated.

**NOTE**
An error same as the one document above is already present in the `Trycycler-github issues` - at A similar (same) error - **unresolved** in Trycycler github issue - https://github.com/rrwick/Trycycler/issues/48

        - Possible alternate solution(s) 
          - Identify and rectify the "segmentation fault" 
          - if the above argument holds (that the output generated is good), avoid exciting due to a non-zero exit (force exit 0) and continue 
          I have tried a few options
         1. `trap 'exit 0' SIGSEGV`
         traps the segmentation fault signal (SIGSEGV) and forces the script to exit with a status of 0.
        2. Force `exit 0` irrespective of the command result
        The above do not seem to do the job- Will try again
          
        
**To Reproduce**
Run barcodes mentioned above from `run_trycycler_cluster.nf` steps onwards

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Package versions implicated in the error (torch, versions, etc)

**Additional context**
An error same as the one document above is already present in the `Trycycler-github issues` - at A similar (same) error - **unresolved** in Trycycler github issue - https://github.com/rrwick/Trycycler/issues/48

**Comment by nandan75** [comment]
Tried the following options (in this order) - **Problem still unresolved** 
- Details in [Implementation document](https://unisyd.sharepoint.com/:w:/r/teams/SydneyInformaticsHub2/_layouts/15/Doc.aspx?sourcedoc=%7BED4C5C62-10E9-4B95-A3E5-8CE3CCCEBDCD%7D&file=Implementation_Readme.doc.docx&wdLOR=cC9331425-FC93-F845-AD60-0A030BB2FA83&action=default&mobileredirect=true)
  - **Option 1** Tried with the most updated singularity image for trycycler   **(Failed  same error)**
  - **Option 2A** Testing trycycler local installation from source - on NCI-Gadi user **(Failed at the step of installation of R package - ape)**
  - **Option 2B** Testing trycycler local installation from source  - on local mac **(Failed when installing python library edlib)** 
  - **Option 3** Ignore segmentation fault errors (134) - how do we selectively ignore PIPE fails in Nextflow? 
    Tried - errorStrategy "ignore" - First attempt did not succeed

**Comment by nandan75** [comment]
Next steps:
- Revisit local installation once more to check if the installation problem can be handled differently
- Revisit Option 3 - Did not get to work more with this option - So can put in some more time.
   -  The workaround if local trycycler installation with ape issue cannot be easily resolved is, to  catch the segmentation-related error ; since all required files are created for the next step- continue to python script "classify" and trycycler reconciliation similar to when exit is '0'

**Comment by fredjaya** [comment]
Will need to verify all this, but some dumping some thoughts. 

**Assumption:**
- The output files in `/scratch/er01/ndes8648/pipeline_work/nextflow/PIPE-4747/pipeline/barcode*` reflects this issue

Without the recommended `trycycler subsample` step, the maximum number of contigs per cluster is 2 - one for flye, one for unicycler. The problematic samples (barcode12-15) appear to have only a single cluster output - meaning - there are 2 contigs total and is impossible to generate a tree (https://github.com/rrwick/Trycycler/issues/77#issuecomment-2277108144).  

Next steps:
- [ ] Step through `classify_trycycler_clusters.py` to confirm (maybe write some unit tests) 
- [ ] Discuss adding a `trycyler subsampling` step
