### ISSUE TITLE
Revise trycycler method implementation

### ISSUE THREAD

**Issue by georgiesamaha** [Sydney-Informatics-Hub/ONT-bacpac-nf#43]

**Comment by fredjaya** [comment]
Implementation/fixes brainstorm. Ranked according to quality of assemblies output, according to literature and previous testing here. Noting that there is a trade-off between workflow runtime and added complexity vs. quality, Method 4 > Method 6 might be the most suitable.

$A$ = total number independent assemblies
$n$ = number of subsets per assembler

| Rank | Method                                                          | Implementation/Notes                                                                |
| ---- | --------------------------------------------------------------- | ----------------------------------------------------------------------------------- |
| 1    | Trycycler with 12 independent assemblies + plassembler w/ flye  | Add two more assemblers and subset 3 reads per assembler                            |
| 2    | Trycycler with $A$ independent assemblies + plassembler w/ flye | Add $A/n$ more assemblers and subset $n$ reads per assembler                        |
| 3?   | `bact-builder` falls somewhere here, but..                      | .. has 4 assemblers with 3 subsets each BUT only and always takes the first cluster |
| 4    | Trycycler with 3 independent assemblies + plassembler w/flye    | Add a third assembler, no subsetting                                                |
| 5    | Trycycler with 2 independent assemblies                         | **Current implementation**                                                          |
| 6    | Use flye assembly if trycyler (2x) fails                             | Easiest fix at the cost of assembly quality                                         |
| 7?   | `hybacter`                                                      | Testing returned less complete assemblies compared to consensus approach            |

**Comment by georgiesamaha** [comment]
Tested adjustment of `bin/classify_trycycler_clusters.py` to filter less stringently (case 3) but that messes up at the reconciliation step due to limited contigs. No go.
