### ISSUE TITLE
Problem with trycyler

### ISSUE THREAD

**Issue by fransamsing** [Sydney-Informatics-Hub/ONT-bacpac-nf#60]
**Describe the bug**
Pipeline stopped running when one of the isolates (barcode15) got to 'CLASSIFYING CONTIGS: barcode15' using trycycler. Removed the problematic isolated, and the pipeline continued with no issue. Could be related to a low number of reads (150K), although barcode10 had less (~105K) and continued without issues. Those two were the isolates with lowest coverage. 

**To Reproduce**
1. uploaded new data to /scratch/tj48/fs9163/new_data
2. bash test/run_test.sh
3. ERROR ~ Error executing process > 'classify_trycycler (CLASSIFYING CONTIGS: barcode15)'

Caused by:
  Missing output file(s) `barcode15_for_reconciliation/*` expected by process `classify_trycycler (CLASSIFYING CONTIGS: barcode15)`

Command executed:
  classify_trycycler_clusters.py \
    barcode15

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /scratch/tj48/fs9163/ONT-bacpac-nf/work/0e/5aa4e468f4e6be068af92b004115c9

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`

 -- Check '.nextflow.log' file for details

**Environment (please complete the following information):**
 - Gadi

**Comment by fredjaya** [comment]
Hi @fransamsing, in that work dir, is there either a `barcode15_cluster/cluster_list.txt` or `barcode15_cluster/contigs.phylip` file? If so, could you check how many contigs there are? e.g. in `contigs.phylip`, the first line should be a number with the number of contigs.

**Comment by fransamsing** [comment]
Thanks Fred, I will have to run it again to check! I needed all the other assemblies for student project, so now that's done. I run the pipeline again in 15 included, and drop the files here ...

**Comment by fransamsing** [comment]
49 clusters.  
![Uploading Screenshot 2024-10-15 at 2.02.32 PM.png…]()

**Comment by fransamsing** [comment]
Hello, just reporting this issue again with a new set of samples: 

it is probably related to coverage (number of reads)


ERROR ~ Error executing process > 'classify_trycycler (CLASSIFYING CONTIGS: barcode13)'

Caused by:
  Missing output file(s) `barcode13_for_reconciliation/*` expected by process `classify_trycycler (CLASSIFYING CONTIGS: barcode13)`


Command executed:

  classify_trycycler_clusters.py \
    barcode13

Command exit status:
  0

Command output:
  (empty)

Work dir:
  /scratch/tj48/fs9163/ONT-bacpac-nf/work/35/e4d91984f3a9a353b8daa78d1fa977

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

**Comment by fredjaya** [comment]
I think both of these issues have been fixed in the branch i'm working on - will double check with you once these have been incorporated
